import { TLogItem } from "@/services/types";
import { ApprovedStep, Service } from "@/types";

export const INITIAL_SERVICES: Service[] = [
  {
    id: "gitlab",
    name: "GitLab",
    status: "connected",
    scope: "read_api",
    logo: "/gitlab-logo.svg",
    logoWidth: 36,
    logoHeight: 36,
    connectLabel: "Connect GitLab",
  },
  {
    id: "slack",
    name: "Slack",
    status: "disconnected",
    scope: "",
    logo: "/slack-logo.svg",
    logoWidth: 44,
    logoHeight: 44,
    connectLabel: "Connect Slack",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    status: "connected",
    scope: "https://www.googleapis.com/auth/calendar.events, openid",
    logo: "/google-calendar.svg",
    logoWidth: 36,
    logoHeight: 36,
    connectLabel: "Connect Google",
  },
];

export const INITIAL_STEPS: Array<ApprovedStep> = [
  {
    id: "retrieve_gitlab_issue",
    label: "retrieve_gitlab_issue",
    required: true,
    checked: false,
  },
  {
    id: "generate_incident_summary",
    label: "generate_incident_summary",
    required: true,
    checked: true,
  },
  {
    id: "send_slack_notification",
    label: "send_slack_notification",
    required: true,
    checked: true,
  },
  {
    id: "schedule_calendar_meeting",
    label: "schedule_calendar_meeting",
    required: false,
    checked: true,
  },
];

export const AUDIT_ENTRIES: TLogItem[] = [
  {
    action: "GitLab Issue Read",
    service: "GitLab",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-04-02 18:22",
    status: "success",
    step_up_required: false,
    detail: "",
    workflow_id: "wf_001",
    approval_state: "approved",
    failure_reason: "",
  },
  {
    action: "Incident Summary Generated",
    service: "Luvira Guardian",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-04-02 18:22",
    status: "success",
    step_up_required: false,
    detail: "",
    workflow_id: "wf_001",
    approval_state: "approved",
    failure_reason: "",
  },
  {
    action: "Slack Message Posted",
    service: "Slack",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-04-02 18:23",
    status: "success",
    step_up_required: true,
    detail: "",
    workflow_id: "wf_001",
    approval_state: "approved",
    failure_reason: "",
  },
  {
    action: "Calendar Event Created",
    service: "Google Calendar",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-04-02 18:23",
    status: "success",
    step_up_required: false,
    detail: "",
    workflow_id: "wf_001",
    approval_state: "approved",
    failure_reason: "",
  },
  {
    action: "GitLab Issue Read",
    service: "GitLab",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-04-01 09:14",
    status: "success",
    step_up_required: false,
    detail: "",
    workflow_id: "wf_002",
    approval_state: "approved",
    failure_reason: "",
  },
  {
    action: "Slack Message Posted",
    service: "Slack",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-04-01 09:15",
    status: "failed",
    step_up_required: false,
    detail: "",
    workflow_id: "wf_002",
    approval_state: "approved",
    failure_reason: "Token expired",
  },
  {
    action: "Token Revoked",
    service: "Google Calendar",
    agent_id: "user_01",
    user_id: "user_01",
    timestamp: "2026-03-30 14:07",
    status: "success",
    step_up_required: false,
    detail: "",
    workflow_id: "",
    approval_state: "approved",
    failure_reason: "",
  },
  {
    action: "Calendar Event Created",
    service: "Google Calendar",
    agent_id: "luvira-guardian",
    user_id: "user_01",
    timestamp: "2026-03-29 11:52",
    status: "success",
    step_up_required: true,
    detail: "",
    workflow_id: "wf_003",
    approval_state: "approved",
    failure_reason: "",
  },
];
